# Generated by Django 4.2 on 2026-06-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_task_title_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(0, "Very Urgent"), (1, "Urgent"), (2, "Whenever")], default=2
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
