# Generated by Django 4.2 on 2026-06-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_task_priority_task_updated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "Very Urgent"), (1, "Urgent"), (2, "Whenever")], default=2
            ),
        ),
    ]
